// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proApiV1LayerType.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum RVData_API_v1_LayerType: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case audio // = 0
  case props // = 1
  case messages // = 2
  case announcements // = 3
  case slide // = 4
  case media // = 5
  case videoInput // = 6
  case UNRECOGNIZED(Int)

  init() {
    self = .audio
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .audio
    case 1: self = .props
    case 2: self = .messages
    case 3: self = .announcements
    case 4: self = .slide
    case 5: self = .media
    case 6: self = .videoInput
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .audio: return 0
    case .props: return 1
    case .messages: return 2
    case .announcements: return 3
    case .slide: return 4
    case .media: return 5
    case .videoInput: return 6
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [RVData_API_v1_LayerType] = [
    .audio,
    .props,
    .messages,
    .announcements,
    .slide,
    .media,
    .videoInput,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension RVData_API_v1_LayerType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "audio"),
    1: .same(proto: "props"),
    2: .same(proto: "messages"),
    3: .same(proto: "announcements"),
    4: .same(proto: "slide"),
    5: .same(proto: "media"),
    6: .same(proto: "video_input"),
  ]
}
