// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proApiV1TimelineOperation.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum RVData_API_v1_TimelineOperation: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case play // = 0
  case pause // = 1
  case rewind // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .play
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .play
    case 1: self = .pause
    case 2: self = .rewind
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .play: return 0
    case .pause: return 1
    case .rewind: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [RVData_API_v1_TimelineOperation] = [
    .play,
    .pause,
    .rewind,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension RVData_API_v1_TimelineOperation: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "play"),
    1: .same(proto: "pause"),
    2: .same(proto: "rewind"),
  ]
}
