import AppKit
import Foundation
import SwiftProtobuf

struct RoundTripChord: Equatable {
    let chord: String
    let start: Int32
    let end: Int32
}

struct RoundTripTextElement: Equatable {
    let sectionName: String
    let sectionID: String
    let slideNumber: Int
    let cueID: String
    let elementIndex: Int
    let elementID: String
    let plainText: String
    let rtfData: Data
    let chords: [RoundTripChord]
}

struct RoundTripSection: Equatable {
    let name: String
    let id: String
    let cueIDs: [String]
}

struct RoundTripArrangement: Equatable {
    let name: String
    let id: String
    let groupIDs: [String]
}

struct RoundTripSnapshot {
    let sections: [RoundTripSection]
    let textElements: [RoundTripTextElement]
    let arrangements: [RoundTripArrangement]
}

struct RoundTripCategory {
    let name: String
    var differences: [String] = []

    var isSame: Bool {
        differences.isEmpty
    }
}

@main
struct RoundTripHarness {
    static func main() async {
        do {
            try await run()
        } catch {
            print("ROUNDTRIP HARNESS FAILED")
            print("\(type(of: error)): \(error)")
            Foundation.exit(1)
        }
    }

    @MainActor
    private static func run() async throws {
        let inputPath = CommandLine.arguments.dropFirst().first ?? "/Users/adamhill/Desktop/Test Chord Song_chords.pro"
        let inputURL = URL(fileURLWithPath: inputPath)
        let workDirectory = URL(fileURLWithPath: "/tmp/pro7chords-roundtrip", isDirectory: true)
        let workingInputURL = workDirectory.appendingPathComponent(inputURL.lastPathComponent)
        let outputURL = workDirectory.appendingPathComponent("Updated_\(inputURL.lastPathComponent)")

        print("=== Pro7Chords Round-Trip Harness ===")
        print("Golden input:      \(inputURL.path)")
        print("Working input copy: \(workingInputURL.path)")
        print("Output:            \(outputURL.path)")
        print("Save path note: FileManagerService.saveFile currently hardcodes Updated_<input filename> beside currentFileURL.")

        let originalInputBytes = try Data(contentsOf: inputURL)
        let originalPresentation = try RVData_Presentation(serializedBytes: originalInputBytes)
        let originalSnapshot = snapshot(originalPresentation)

        try FileManager.default.createDirectory(at: workDirectory, withIntermediateDirectories: true)
        if FileManager.default.fileExists(atPath: workingInputURL.path) {
            try FileManager.default.removeItem(at: workingInputURL)
        }
        if FileManager.default.fileExists(atPath: outputURL.path) {
            try FileManager.default.removeItem(at: outputURL)
        }
        try originalInputBytes.write(to: workingInputURL, options: .atomic)

        let fileManager = FileManagerService()

        let loadedLyrics = try await fileManager.loadFile(url: inputURL)
        let chordMap = extractChordMapLikeEditor(from: loadedLyrics)
        fileManager.currentFileURL = workingInputURL

        print("\n=== Round Trip ===")
        print("Loaded display text characters: \(loadedLyrics.count)")
        print("Chord-map entries generated by current editor logic: \(chordMap.count)")

        try await fileManager.saveFile(lyrics: loadedLyrics, chordMap: chordMap)

        guard FileManager.default.fileExists(atPath: outputURL.path) else {
            throw HarnessError.outputMissing(outputURL.path)
        }

        let afterInputBytes = try Data(contentsOf: inputURL)
        print("Input byte-for-byte untouched: \(afterInputBytes == originalInputBytes ? "YES" : "NO")")

        let roundTrippedBytes = try Data(contentsOf: outputURL)
        let roundTrippedPresentation = try RVData_Presentation(serializedBytes: roundTrippedBytes)
        let roundTrippedSnapshot = snapshot(roundTrippedPresentation)

        let categories = compare(original: originalSnapshot, roundTripped: roundTrippedSnapshot)

        print("\n=== Pass/Fail By Category ===")
        for category in categories {
            print("\(category.name): \(category.isSame ? "SAME" : "DIFFERENT")")
        }

        print("\n=== Differences ===")
        for category in categories where !category.isSame {
            print("\n--- \(category.name) ---")
            for difference in category.differences {
                print(difference)
            }
        }

        let allSame = categories.allSatisfy(\.isSame)
        print("\n=== Overall ===")
        print(allSame ? "LOSSLESS ROUND TRIP: YES" : "LOSSLESS ROUND TRIP: NO")
    }

    private static func extractChordMapLikeEditor(from lyrics: String) -> [String: String] {
        var chordMap: [String: String] = [:]
        let sectionPattern = #"---\s*[^-]+\s*---"#
        var slides: [String] = []

        do {
            let regex = try NSRegularExpression(pattern: sectionPattern, options: [])
            let nsString = lyrics as NSString
            let matches = regex.matches(in: lyrics, options: [], range: NSRange(location: 0, length: nsString.length))
            var lastEnd = 0

            for match in matches {
                if match.range.location > lastEnd {
                    let contentRange = NSRange(location: lastEnd, length: match.range.location - lastEnd)
                    slides.append(nsString.substring(with: contentRange))
                }

                lastEnd = match.range.location + match.range.length
            }

            if lastEnd < nsString.length {
                slides.append(nsString.substring(from: lastEnd))
            }

            if matches.isEmpty {
                slides = [lyrics]
            }
        } catch {
            slides = [lyrics]
        }

        for (index, slideText) in slides.enumerated() {
            let cleanText = slideText.trimmingCharacters(in: .whitespacesAndNewlines)
            if cleanText.isEmpty {
                continue
            }

            if cleanText.contains("[") && cleanText.contains("]") {
                chordMap[String(index)] = cleanText
            }
        }

        return chordMap
    }

    private static func snapshot(_ presentation: RVData_Presentation) -> RoundTripSnapshot {
        var cueMap: [String: RVData_Cue] = [:]
        for cue in presentation.cues {
            cueMap[cue.uuid.string] = cue
        }

        let sections = presentation.cueGroups
            .filter(\.hasGroup)
            .map { cueGroup in
                RoundTripSection(
                    name: cueGroup.group.name,
                    id: cueGroup.group.uuid.string,
                    cueIDs: cueGroup.cueIdentifiers.map(\.string)
                )
            }

        var textElements: [RoundTripTextElement] = []

        for cueGroup in presentation.cueGroups where cueGroup.hasGroup {
            for (cueIndex, cueID) in cueGroup.cueIdentifiers.enumerated() {
                guard let cue = cueMap[cueID.string] else {
                    continue
                }

                for action in cue.actions {
                    guard case .slide(let slideType) = action.actionTypeData,
                          case .presentation(let presentationSlide) = slideType.slide else {
                        continue
                    }

                    for (elementIndex, slideElement) in presentationSlide.baseSlide.elements.enumerated() {
                        let element = slideElement.element
                        guard element.hasText else {
                            continue
                        }

                        let text = element.text
                        textElements.append(
                            RoundTripTextElement(
                                sectionName: cueGroup.group.name,
                                sectionID: cueGroup.group.uuid.string,
                                slideNumber: cueIndex + 1,
                                cueID: cueID.string,
                                elementIndex: elementIndex,
                                elementID: element.uuid.string,
                                plainText: decodeRTF(text.rtfData),
                                rtfData: text.rtfData,
                                chords: text.attributes.customAttributes
                                    .filter { !$0.chord.isEmpty }
                                    .map {
                                        RoundTripChord(
                                            chord: $0.chord,
                                            start: $0.range.start,
                                            end: $0.range.end
                                        )
                                    }
                            )
                        )
                    }
                }
            }
        }

        let arrangements = presentation.arrangements.map {
            RoundTripArrangement(
                name: $0.name,
                id: $0.uuid.string,
                groupIDs: $0.groupIdentifiers.map(\.string)
            )
        }

        return RoundTripSnapshot(sections: sections, textElements: textElements, arrangements: arrangements)
    }

    private static func compare(original: RoundTripSnapshot, roundTripped: RoundTripSnapshot) -> [RoundTripCategory] {
        [
            compareSections(original.sections, roundTripped.sections),
            comparePlainText(original.textElements, roundTripped.textElements),
            compareChordPositions(original.textElements, roundTripped.textElements),
            compareRTF(original.textElements, roundTripped.textElements),
            compareArrangements(original.arrangements, roundTripped.arrangements)
        ]
    }

    private static func compareSections(_ original: [RoundTripSection], _ roundTripped: [RoundTripSection]) -> RoundTripCategory {
        var category = RoundTripCategory(name: "section names")

        if original.count != roundTripped.count {
            category.differences.append("Section count changed: before \(original.count), after \(roundTripped.count)")
        }

        for index in 0..<max(original.count, roundTripped.count) {
            let before = original[safe: index]
            let after = roundTripped[safe: index]

            if before != after {
                category.differences.append(
                    """
                    Section[\(index)] changed:
                      before: \(describe(before))
                      after:  \(describe(after))
                    """
                )
            }
        }

        return category
    }

    private static func comparePlainText(_ original: [RoundTripTextElement], _ roundTripped: [RoundTripTextElement]) -> RoundTripCategory {
        var category = RoundTripCategory(name: "plain text incl. whitespace")
        compareElements(original, roundTripped) { before, after in
            guard before.plainText != after.plainText else {
                return nil
            }

            return """
            \(elementLabel(before)) plain text changed:
              before(\(before.plainText.count)): "\(visible(before.plainText))"
              after(\(after.plainText.count)):  "\(visible(after.plainText))"
            """
        }.forEach { category.differences.append($0) }

        return category
    }

    private static func compareChordPositions(_ original: [RoundTripTextElement], _ roundTripped: [RoundTripTextElement]) -> RoundTripCategory {
        var category = RoundTripCategory(name: "chord positions")
        compareElements(original, roundTripped) { before, after in
            guard before.chords != after.chords else {
                return nil
            }

            return """
            \(elementLabel(before)) chord attributes changed:
              before: \(describe(before.chords))
              after:  \(describe(after.chords))
            """
        }.forEach { category.differences.append($0) }

        return category
    }

    private static func compareRTF(_ original: [RoundTripTextElement], _ roundTripped: [RoundTripTextElement]) -> RoundTripCategory {
        var category = RoundTripCategory(name: "RTF/formatting")
        compareElements(original, roundTripped) { before, after in
            guard before.rtfData != after.rtfData else {
                return nil
            }

            return """
            \(elementLabel(before)) RTF changed:
              before bytes: \(before.rtfData.count), sha256: \(sha256(before.rtfData))
              after bytes:  \(after.rtfData.count), sha256: \(sha256(after.rtfData))
              before RTF preview: "\(visible(rtfPreview(before.rtfData)))"
              after RTF preview:  "\(visible(rtfPreview(after.rtfData)))"
            """
        }.forEach { category.differences.append($0) }

        return category
    }

    private static func compareArrangements(_ original: [RoundTripArrangement], _ roundTripped: [RoundTripArrangement]) -> RoundTripCategory {
        var category = RoundTripCategory(name: "arrangement")

        if original.count != roundTripped.count {
            category.differences.append("Arrangement count changed: before \(original.count), after \(roundTripped.count)")
        }

        for index in 0..<max(original.count, roundTripped.count) {
            let before = original[safe: index]
            let after = roundTripped[safe: index]

            if before != after {
                category.differences.append(
                    """
                    Arrangement[\(index)] changed:
                      before: \(describe(before))
                      after:  \(describe(after))
                    """
                )
            }
        }

        return category
    }

    private static func compareElements(
        _ original: [RoundTripTextElement],
        _ roundTripped: [RoundTripTextElement],
        difference: (RoundTripTextElement, RoundTripTextElement) -> String?
    ) -> [String] {
        var differences: [String] = []

        if original.count != roundTripped.count {
            differences.append("Text element count changed: before \(original.count), after \(roundTripped.count)")
        }

        for index in 0..<max(original.count, roundTripped.count) {
            guard let before = original[safe: index] else {
                differences.append("Added text element[\(index)]: \(elementLabel(roundTripped[index]))")
                continue
            }

            guard let after = roundTripped[safe: index] else {
                differences.append("Removed text element[\(index)]: \(elementLabel(before))")
                continue
            }

            if identity(before) != identity(after) {
                differences.append(
                    """
                    Text element identity[\(index)] changed:
                      before: \(identity(before))
                      after:  \(identity(after))
                    """
                )
            }

            if let elementDifference = difference(before, after) {
                differences.append(elementDifference)
            }
        }

        return differences
    }

    private static func decodeRTF(_ data: Data) -> String {
        if let attributedString = try? NSAttributedString(
            data: data,
            options: [.documentType: NSAttributedString.DocumentType.rtf],
            documentAttributes: nil
        ) {
            return attributedString.string
        }

        return "<RTF_DECODE_FAILED>"
    }

    private static func rtfPreview(_ data: Data) -> String {
        String(decoding: data.prefix(500), as: UTF8.self)
    }

    private static func visible(_ text: String) -> String {
        text
            .replacingOccurrences(of: " ", with: "·")
            .replacingOccurrences(of: "\t", with: "⇥")
            .replacingOccurrences(of: "\r", with: "␍")
            .replacingOccurrences(of: "\n", with: "⏎\n")
    }

    private static func describe(_ section: RoundTripSection?) -> String {
        guard let section else {
            return "<missing>"
        }

        return "name=\"\(section.name)\", id=\(section.id), cueIDs=\(section.cueIDs)"
    }

    private static func describe(_ arrangement: RoundTripArrangement?) -> String {
        guard let arrangement else {
            return "<missing>"
        }

        return "name=\"\(arrangement.name)\", id=\(arrangement.id), groupIDs=\(arrangement.groupIDs)"
    }

    private static func describe(_ chords: [RoundTripChord]) -> String {
        if chords.isEmpty {
            return "[]"
        }

        return chords
            .map { "\(String(reflecting: $0.chord))@\( $0.start)-\( $0.end)" }
            .joined(separator: ", ")
    }

    private static func identity(_ element: RoundTripTextElement) -> String {
        "\(element.sectionName)|\(element.sectionID)|slide \(element.slideNumber)|cue \(element.cueID)|element \(element.elementIndex)|\(element.elementID)"
    }

    private static func elementLabel(_ element: RoundTripTextElement) -> String {
        "[\(element.sectionName) / Slide \(element.slideNumber) / element \(element.elementIndex) / \(element.elementID)]"
    }

    private static func sha256(_ data: Data) -> String {
        // FNV-1a is enough for a diagnostic fingerprint and avoids adding CryptoKit to the compile command.
        var hash: UInt64 = 0xcbf29ce484222325
        for byte in data {
            hash ^= UInt64(byte)
            hash &*= 0x100000001b3
        }
        return String(format: "%016llx", hash)
    }
}

enum HarnessError: Error {
    case outputMissing(String)
}

extension Collection {
    subscript(safe index: Index) -> Element? {
        indices.contains(index) ? self[index] : nil
    }
}
